CREATE TABLE esp_dados(
id INT AUTO_INCREMENT PRIMARY KEY,
temperatura FLOAT,
umidade FLOAT,
luminosidade FLOAT,
data_registro DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE usuario_dados(
id INT AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(30) NOT NULL,
email VARCHAR(50) NOT NULL UNIQUE,
senha VARCHAR(100) NOT NULL,
PRIMARY KEY (id)
);
